// Auto-generated by installer — do not edit manually
// Replace CHANGE_ME_TO_RANDOM_STRING with the value of DIAGNOSE_TOKEN from ebmpro_api/config.php
const DIAGNOSE_TOKEN = 'CHANGE_ME_TO_RANDOM_STRING';
