<?php
// ebmpro_api/config.php — generated by the installer.
// Do not edit this file manually; run /install/ to regenerate it.
// NOTE: Replace DB_NAME, DB_USER, DB_PASS with your actual credentials
//       after running the installer. Do not commit real credentials to version control.

define('SITE_URL', 'https://shanemcgee.biz');
define('APP_PATH', '/ebmpro/');
define('API_PATH', '/ebmpro_api/');
define('TRACK_URL', 'https://shanemcgee.biz/track/open.php');

// Database configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'your_database_name');
define('DB_USER', 'your_username');
define('DB_PASS', 'your_password');

try {
    $pdo = new PDO(
        'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4',
        DB_USER,
        DB_PASS
    );
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    http_response_code(500);
    exit('Database connection error.');
}
