<?php
// This file is generated by the installer.
// Run /install/ to configure the database.
define('DB_HOST', 'localhost');
define('DB_NAME', '');
define('DB_USER', '');
define('DB_PASS', '');
define('APP_SECRET', 'changeme_run_installer');
